apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-api
  labels:
    app: data-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-api
  template:
    metadata:
      labels:
        app: data-api
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'webapp'
        vault.hashicorp.com/auth-path: 'auth/kubernetes-rriv'
        vault.hashicorp.com/agent-inject-secret-credentials.txt: 'secret/data/dev-timescale-creds'
        vault.hashicorp.com/agent-inject-template-credentials: |
          {{ with secret "secret/data/dev-timescale-creds" }}
          export DATABASE_URL={{ .Data.data.databae_url }}
          {{ end }}

    spec:
      serviceAccountName: internal-app
      imagePullSecrets:
        - name: registry-rriv
      containers:
        - name: data-api
          image: registry.digitalocean.com/rriv/data-api 
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_SCHEMA
              value: rriv
