apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-api
  labels:
    app: data-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-api
  template:
    metadata:
      labels:
        app: data-api
    spec:
      imagePullSecrets:
        - name: registry-rriv
      containers:
        - name: data-api
          image: registry.digitalocean.com/rriv/data-api 
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              value: notspecified
            - name: DATABASE_SCHEMA
              value: rriv
